name: Kittens Bot

on:
  issues:
    types:
      - closed
  pull_request:
    types:
      - closed

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
    - name: Send kittens on issue/PR close
      uses: peter-evans/create-or-update-comment@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number || github.event.pull_request.number }}
        body: |
          <img src="https://camo.githubusercontent.com/fa1024ceec72649e6eada47b6a0704fb0241eafb16a82ff4565d11307e5de5ce/68747470733a2f2f692e696d6775722e636f6d2f663035536a624e2e676966" width="100%">
